### ISSUE TITLE
Latest TL scheme supported

### ISSUE THREAD

**Issue by davidcon** [MRebati/TLSharp.NetStandard#1]
Excuse me, could you tell me which layer is implemented?
Thank you very much.

**Comment by MRebati** [comment]
This package has implemented Asterisk AMI interface methods.
You can use event listeners and also cast actions toward Asterisk.

**Comment by MRebati** [comment]
The API is .net-framework implementation from Telethon in python.
You can connect to Telegram API as a Telegram Client and you can also use the Bot Interface which has its own methods to control the bot
